### ISSUE TITLE
Lines without semicolons are put on the same line

### ISSUE THREAD

**Issue by kemonologic** [sanboxrunner/gml_fmt#29]
Lines without semicolons appear to have their newlines removed until the next line with a semicolon is hit, rather than having a semicolon added. 
```
global.roundOver=true
alarm[3]=room_speed/10;
audio_stop_sound(aMusicTitle);
```
turns into

```
global.roundOver=true alarm[3]=room_speed/10;
audio_stop_sound(aMusicTitle);
```

**Comment by sanboxrunner** [comment]
Thanks. looking into it now

**Comment by sanboxrunner** [comment]
This ties into a deeper issue in how we handle statement/expression trailing comments. If a statement-expression has a trailing comment after `;` then we correctly capture it, but a trailing comment without a `;` has trouble being captured.

The best solution is to let it break and fix it, rather than trying to build a levy against errors. Levies are hard to maintain but rebuilding is relatively simple. We can do that in the print_expression_statement section.

**Comment by sanboxrunner** [comment]
Solved. Tomorrow morning i'll push a new update out now.

If you're inpatient, the master branch has the new updates if you want to build from source. Binaries tomorrow
